{% set name = "onedatafilerestclient" %}
{% set version = "25.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onedatafilerestclient-{{ version }}.tar.gz
  sha256: 8eee3899ddeaed457b6da564588bd299e5bb3a6afe10d75cb08690c0eba80b27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging
    - requests
    - typing_extensions >=4.3.0

test:
  imports:
    - onedatafilerestclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/onedata/onedatafilerestclient
  summary: Onedata REST file API client
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bgruening
