{% set name = "onedatafilerestclient" %}
{% set version = "21.2.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onedatafilerestclient-{{ version }}.tar.gz
  sha256: 235ae8130a8517314260025e5d43a82d95516db12208d618ead9193b5e5784c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging
    - requests
    - typing_extensions >=4.3.0

test:
  imports:
    - onedatafilerestclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/onedata/onedatafilerestclient
  summary: Onedata REST file API client
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bgruening
